# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sunny-vue-app
  namespace: sunny-test-namespace
spec:
  selector:
    app: sunny-vue-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
